info/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name="Index")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/models.py
import profile
from tabnanny import verbose
from turtle import update
from unicodedata import category
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Home(models.Model):
    name = models.CharField(max_length=20, verbose_name = 'Имя')
    greetings_1 = models.CharField(max_length=5, verbose_name = 'Приветствие 1')
    greetings_2 = models.CharField(max_length=8, verbose_name = 'Приветствие 2')
    image = models.ImageField(upload_to = 'pic/', verbose_name = 'Фото')
    update_time = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страница "Главная"'
        verbose_name_plural = 'Страницы "Главная"'

class About(models.Model):
    heading = models.CharField(max_length=50, verbose_name = 'Заголовок')
    career = models.CharField(max_length=20, verbose_name = 'Опыт работы')
    description = models.TextField(blank=False, verbose_name = 'Описание')
    profile_img = models.ImageField(upload_to='pic/', verbose_name = 'Фото')
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.career

    class Meta:
        verbose_name = 'Страница "Обо мне"'
        verbose_name_plural = 'Страницы "Обо мне"'

class Profile(models.Model):
    about = models.ForeignKey(About, on_delete = models.CASCADE)
    social_name = models.CharField(max_length = 10)
    link = models.URLField(max_length = 200)

class Category(models.Model):
    name = models.CharField(max_length = 20)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Skill(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    skill_name = models.CharField(max_length = 20)

class Portfolio(models.Model):
    image = models.ImageField(upload_to = 'pic/')
    link = models.URLField(max_length = 200)

    def __str___(self):
        return f'Portfolio{self.id}'

    class Meta:
        verbose_name = 'Мое портфолио'
        verbose_name_plural = 'Мои портфолио'

info/views.py
from django.shortcuts import render
from .models import *

def index(request):

# Home
    home = Home.objects.latest('update_time')

# About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

# Skills
    categories = Category.objects.all()

# Portfolios
    portfolios = Portfolio.objects.all()

    context = {
        'home' : home,
        'about' : about,
        'profiles' : profiles,
        'categories' : categories,
        'portfolios' : portfolios,
    }

    return render(request, 'info/main.html', context)

info/templates/info/main.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'info/img/main.ico' %}" type ="image/x-icon">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'info/css/styles.css' %}" >

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
        

        <title>Портфолио</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="{% url 'Index' %}" class="nav__logo">{{home.name}}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">В начало</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">Обо мне</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Навыки</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Мои работы</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Контакты</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <img src="{{home.image.url}}" alt="" class="home__img">

                    <h1 class="home__title"><span>{{home.greetings_1}}</span><br>{{home.greetings_2}}</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Листать вниз</a>
                    </div>

                    
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">Обо мне</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{{about.profile_img.url}}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{about.heading}}</h2>
                        <span class="about__profession">{{about.career}}</span>
                        <p class="about__text">{{about.description}}</p>

                        <div class="about__social">
                            {% for profile in profiles %}

                                <a href="{{profile.link}}" class="about__social-icon">
                                    <i class='bx bxl-{{profile.social_name}}' ></i>
                                </a>
                            {% endfor %}
                                                        
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Навыки</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        
                            <h3 class="skills__subtitle">{{category.name}}</h3>
                                {% for skill in category.skill_set.all %}
                                    <span class="skills__name">{{skill.skill_name}}</span>
                                {% endfor %}
                        {% endfor %}
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'info/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Мои работы</h2>

                
                <div class="portfolio__container bd-grid">

                    {% for portfolio in portfolios %}
                        <div class="portfolio__img">
                            <img src="{{portfolio.image.url}}" alt="">

                            <div class="portfolio__link">
                                <a href="{{portfolio.link}}" class="portfolio__link-name">Подробнее</a>
                            </div>
                        </div>
                    {% endfor %}
                                                             
                </div>
                
            </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Контакты</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">tundrik_2210@mail.ru</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">г. Кострома</span>                        
                    </div>

                    <div class="contact__info">

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+7-910-000-00-00</span>

                        <h3 class="contact__subtitle">WhatsApp</h3>
                        <span class="contact__text">+7-910-000-00-00</span>
                    </div>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">{{home.name}}</h2>
                    <p class="footer__text">Меня зовут {{home.name}} и это моя страница</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">Искать</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Главная</a></li>
                        <li><a href="#about" class="footer__link">Обо мне</a></li>
                        <li><a href="#skills" class="footer__link">Навыки</a></li>
                        <li><a href="#portfolio" class="footer__link">Мои рaботы</a></li>
                        <li><a href="#Contact" class="footer__link">Контакты</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">Я в соцсетях</h2>
                        {% for profile in profiles %}
                            <a href="{{profile.link}}" class="footer__social"><i class='bx bxl-{{profile.social_name}}' ></i></a>
                        {% endfor %}
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'info/js/main.js' %}"></script>
    </body>
</html>